package com.example.lyfstile

const val EMAIL = "email"
const val PASSWORD = "password"
const val PASSWORD_CONFIRMED = "password_confirmed"
const val FIRST_NAME = "first_name"
const val LAST_NAME = "last_name"
const val AGE = "age"
const val SEX = "sex"
const val HEIGHT = "height"
const val WEIGHT = "weight"
const val COUNTRY = "country"
const val CITY = "city"
const val BMI = "bmi"
const val FIRST_LAST_NAME_SCREEN = "first_last_name"
const val AGE_SEX_SCREEN = "age_sex"
const val HEIGHT_WEIGHT_SCREEN = "height_weight"
const val COUNTRY_CITY_SCREEN = "country_city"
const val ACTION_BAR = "action_bar"
const val USER_DATA = "user_data"
const val PROFILE_PIC = "profile_pic"